// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/longln/go-simplebank/internal/controller"
	"github.com/longln/go-simplebank/internal/repository"
	"github.com/longln/go-simplebank/internal/service"
)

// Injectors from account.wire.go:

func InitUserRouterHandler() (*controller.AccountController, error) {
	iAccountRepository := repository.NewAccountRepository()
	iAccountService := service.NewAccountService(iAccountRepository)
	accountController := controller.NewController(iAccountService)
	return accountController, nil
}
